name: BTD

on: 
  workflow_dispatch:

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello World
        run: echo Hello, world!
        
      - name: Checkout tools repo
        uses: actions/checkout@v3
        with:
          repository: velivalab/SampleRepo
        
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Say Test World
        run: echo Test, world!
        
        
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Say Deploy World
        run: echo Deploy, !
